openapi: 3.0.3
info:
  title: eth-parser
  version: 1.0.0
  contact: {}
servers:
  - url: localhost
paths:
  /subscribe:
    post:
      summary: Subscribe
      description: Subscribe
      operationId: subscribe
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  example: "0x95222290DD7278Aa3Ddd389Cc1E1d165CC4BAfe5"
            example:
              address: "0x95222290DD7278Aa3Ddd389Cc1E1d165CC4BAfe5"
      responses:
        "200":
          description: ""
  /transactions:
    get:
      summary: Transactions
      description: Transactions
      operationId: transactions
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  example: "0x95222290DD7278Aa3Ddd389Cc1E1d165CC4BAfe5"
            example:
              address: "0x95222290DD7278Aa3Ddd389Cc1E1d165CC4BAfe5"
      responses:
        "200":
          description: ""
  /block:
    get:
      summary: Latest Block
      description: Latest Block
      operationId: latestBlock
      responses:
        "200":
          description: ""
  /subscriber:
    get:
      summary: Subscriber
      description: Subscriber
      operationId: subscriber
      responses:
        "200":
          description: ""
tags: []
